pKVM: x86: Expose kvm_setup_xss_caps to pKVM to fix linking
After commit b5a02290ee3a ("KVM: x86: Explicitly configure supported
XSS from {svm,vmx}_set_cpu_caps()"), the pKVM hypervisor build fails
with an undefined reference to `kvm_setup_xss_caps`.

Move `kvm_setup_xss_caps` outside the `#ifndef __PKVM_HYP__` block
to ensure it is compiled and available for the pKVM hypervisor,
resolving the linking error.

At the same time drop configuration related to XSS from
pkvm_x86_vendor_init() as right now the kvm_setup_xss_caps() which
handles that is called by vmx_set_cpu_caps() in vmx_hardware_setup() for
both KVM and pKVM.

Fixes: b5a02290ee3a ("KVM: x86: Explicitly configure supported XSS from {svm,vmx}_set_cpu_caps()")

Signed-off-by: Grzegorz Jaszczyk <jaszczyk@google.com>