pkvm: x86: pkvm_image.h not required in pkvm_init.c
More over it causes build errors with minimal config that I was using to
build a kernel for a busybox vm

In file included from ../arch/x86/kvm/vmx/pkvm_init.c:7:
../arch/x86/include/asm/pkvm_image.h:52:46: error: array type has incomplete element type ‘struct exception_table_entry’
   52 | extern struct exception_table_entry pkvm_sym(__start___ex_table)[];
      |                                              ^~~~~~~~~~~~~~~~~~
../arch/x86/include/asm/pkvm_image.h:24:41: note: in definition of macro ‘pkvm_sym’
   24 | #define pkvm_sym(sym)                   sym##__pkvm
      |                                         ^~~
../arch/x86/include/asm/pkvm_image.h:53:46: error: array type has incomplete element type ‘struct exception_table_entry’
   53 | extern struct exception_table_entry pkvm_sym(__stop___ex_table)[];
      |                                              ^~~~~~~~~~~~~~~~~
../arch/x86/include/asm/pkvm_image.h:24:41: note: in definition of macro ‘pkvm_sym’
   24 | #define pkvm_sym(sym)                   sym##__pkvm

exception_table_entry is defined in <asm/extable.h>. Not sure how it
gets included with a bigger config - haven't investigated it yet.

Signed-off-by: Vineeth Pillai <vineethrp@google.com>